name: Bruno Descaves
favicon: null
layout_spectrum: 0.8950058366172016
typography_spectrum: 0.1682241370435804
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.124662552960217
  lightness: 0.46862179855816066
  saturation: 0.1207580070476979
  rhythmicContrast: 0.12156957504339516
purpose: []
